# Generated by Django 4.0 on 2022-02-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('tagline', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='static')),
            ],
        ),
    ]
